# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='site_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='height_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='width_field',
            field=models.IntegerField(default=300),
        ),
    ]
